### ISSUE TITLE
running maser script using docker

### ISSUE THREAD

**Issue by Ankita-1211** [mcfonseca-lab/docker#2]
Hi 

Could you help me with how can I run the run_maser.R script using the docker image.

Right now command I am using is 
docker run mcfonsecalab/rmats Rscript run_maser.R control treated 1 0.05 0.2 JC

It gives me below error 

Error: Problem with `filter()` input `..1`.
i Input `..1` is `FDR < fdr`.
x object 'FDR' not found
Backtrace:
     x
  1. +-base::lapply(...)
  2. | \-global::FUN(X[[i]], ...)
  3. |   \-maser::volcano(maser_obj, type = type, fdr = fdr_threshold, deltaPSI = deltaPSI_threshold)
  4. |     +-dplyr::filter(stats, FDR < fdr, IncLevelDifference > deltaPSI)
  5. |     \-dplyr:::filter.data.frame(...)
  6. |       \-dplyr:::filter_rows(.data, ...)
  7. |         +-base::withCallingHandlers(...)
  8. |         \-mask$eval_all_filter(dots, env_filter)
  9. \-base::.handleSimpleError(...)
 10.   \-dplyr:::h(simpleError(msg, call))
Execution halted

**Comment by PedroBarbosa** [comment]
Hello,

Which version of the docker image are you using ? 

> Error: Problem with `filter()` input `..1`.
> i Input `..1` is `FDR < fdr`.
> x object 'FDR' not found
> Backtrace:

The error seems to be from maser package itself,  probably due to some issue with the input data. This docker image is not designed to run maser out of the box. Rather, It is just intended to have all the software packages related to rMATS splicing analysis installed in one single container. 

The `run_maser.R` script was developed for my personal use, I should probably remove it in the next version to avoid problems like this one.

Anyway, that's how I usually run:
`docker run run_maser.R $label1 $label2 $min_avg_reads $fdr_threshold $deltaPSI_threshold "JC""`, which is similar to what you've set. The script needs you to be within the directory where the rMATS output files are located ([line 28 of the script](https://github.com/mcfonseca-lab/docker/blob/master/rmats/run_maser.R)), and there must exist only 5 files (one for each event type) ending with `JC.txt` (since you set the 6th argument to JC).

Additionally, I strongly advise to change the `min_avg_reads` parameter to a higher value, since the coverage filter is one of the main utilities of the the script. Setting it to 1 renders that filtering useless. From my experience, latest versions of rMATS report a lot of significant events (specially if you set the --novelSS argument). This filter just ensures that significant events with very low coverage are removed. Precisely, the parameter ensures that only events where the maximum between inc/exc isoform on both groups is higher `than min_avg_reads`. I usually set it to 5 or 10 (if I want to be more stringent). You can see at the end how many events were removed by the coverage filtering by counting the lines in the `coverage_filt` folder that's created.

If your error still persists, you can try to debug a little bit deeper by entering the docker image in interactive mode, and changing the script code (e.g. adding prints) to see what's going on. I'm sorry if I can't help much more than this.

Best,
Pedro

**Comment by PedroBarbosa** [comment]
I guess this issue was solved. Closing it for now.
